import { randomUUID } from "crypto";
import type { Salon, Service, Store, User } from "./types";

const now = () => new Date().toISOString();

const makeUser = (data: Partial<User> & Pick<User, "phoneNumber" | "role">) =>
  ({
    id: randomUUID(),
    phoneNumber: data.phoneNumber,
    email: data.email,
    fullName: data.fullName,
    profileImage: data.profileImage,
    role: data.role,
    isVerified: true,
    isBlocked: false,
    lastLogin: undefined,
    createdAt: now(),
    updatedAt: now(),
  }) satisfies User;

export const seedStore = (store: Store): Store => {
  if (store.salons.length > 0) {
    return store;
  }

  const admin = makeUser({
    phoneNumber: "9990000000",
    role: "ADMIN",
    fullName: "SpotMyGlam Admin",
  });
  const owner = makeUser({
    phoneNumber: "9990001111",
    role: "SALON_OWNER",
    fullName: "Noir & Co. Owner",
  });

  const salons: Salon[] = [
    {
      id: randomUUID(),
      ownerId: owner.id,
      name: "Noir & Co. Salon",
      description:
        "Premium salon studio offering precision cuts, signature coloring, and curated styling.",
      phoneNumber: "+91 90000 11111",
      address: "14, Richmond Road, Ashok Nagar",
      city: "Bengaluru",
      state: "Karnataka",
      latitude: 12.9716,
      longitude: 77.5946,
      openingTime: "09:00",
      closingTime: "21:00",
      averageRating: 4.8,
      totalReviews: 248,
      isVerified: true,
      isActive: true,
      categories: ["Hair Care", "Makeup", "Nails"],
      gallery: ["/salon-placeholder.svg"],
      offers: ["Flat ₹200 off on first booking", "Complimentary hair spa on Fridays"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      ownerId: owner.id,
      name: "Studio Blanc",
      description:
        "Minimalist beauty studio focused on skincare rituals, facials, and glow therapies.",
      phoneNumber: "+91 90000 22222",
      address: "7, Indiranagar 100ft Road",
      city: "Bengaluru",
      state: "Karnataka",
      latitude: 12.9784,
      longitude: 77.6408,
      openingTime: "10:00",
      closingTime: "20:30",
      averageRating: 4.6,
      totalReviews: 173,
      isVerified: true,
      isActive: true,
      categories: ["Skin & Facial", "Spa & Massage"],
      gallery: ["/salon-placeholder.svg"],
      offers: ["Glow facial + LED therapy combo", "Free skin consultation"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      ownerId: owner.id,
      name: "Glowline Atelier",
      description:
        "Editorial makeup and styling atelier for events, bridal looks, and premium grooming.",
      phoneNumber: "+91 90000 33333",
      address: "22, MG Road",
      city: "Bengaluru",
      state: "Karnataka",
      latitude: 12.9755,
      longitude: 77.6067,
      openingTime: "08:00",
      closingTime: "22:00",
      averageRating: 4.7,
      totalReviews: 312,
      isVerified: true,
      isActive: true,
      categories: ["Makeup", "Hair Care"],
      gallery: ["/salon-placeholder.svg"],
      offers: ["Bridal trial at 30% off", "Free styling consultation"],
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      ownerId: owner.id,
      name: "Aurum Spa & Nails",
      description:
        "Luxury spa rituals and precision nail artistry with a serene, monochrome vibe.",
      phoneNumber: "+91 90000 44444",
      address: "58, Koramangala 5th Block",
      city: "Bengaluru",
      state: "Karnataka",
      latitude: 12.9352,
      longitude: 77.6245,
      openingTime: "10:30",
      closingTime: "22:30",
      averageRating: 4.5,
      totalReviews: 139,
      isVerified: true,
      isActive: true,
      categories: ["Spa & Massage", "Nails"],
      gallery: ["/salon-placeholder.svg"],
      offers: ["Free nail art with spa combo", "Couple massage ₹999 off"],
      createdAt: now(),
      updatedAt: now(),
    },
  ];

  const services: Service[] = [
    {
      id: randomUUID(),
      salonId: salons[0].id,
      name: "Signature Haircut",
      description: "Precision cut with wash and blow dry.",
      category: "Hair Care",
      durationMinutes: 60,
      price: 899,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[0].id,
      name: "Luxury Hair Spa",
      description: "Deep conditioning ritual with scalp massage.",
      category: "Hair Care",
      durationMinutes: 75,
      price: 1299,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[0].id,
      name: "Editorial Makeup",
      description: "Full glam makeup with premium products.",
      category: "Makeup",
      durationMinutes: 90,
      price: 2499,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[1].id,
      name: "Glow Facial",
      description: "Signature facial with LED therapy.",
      category: "Skin & Facial",
      durationMinutes: 60,
      price: 1599,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[1].id,
      name: "Aromatherapy Massage",
      description: "Full body massage with calming oils.",
      category: "Spa & Massage",
      durationMinutes: 90,
      price: 1999,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[2].id,
      name: "Bridal Makeup Trial",
      description: "Curated bridal look consultation and trial.",
      category: "Makeup",
      durationMinutes: 120,
      price: 2999,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[2].id,
      name: "Keratin Smoothening",
      description: "Frizz-free, glossy smoothening treatment.",
      category: "Hair Care",
      durationMinutes: 150,
      price: 3499,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[3].id,
      name: "Spa Ritual",
      description: "Signature spa ritual with scrub + massage.",
      category: "Spa & Massage",
      durationMinutes: 120,
      price: 2299,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: randomUUID(),
      salonId: salons[3].id,
      name: "Luxury Nail Art",
      description: "Custom monochrome nail art session.",
      category: "Nails",
      durationMinutes: 60,
      price: 999,
      isActive: true,
      createdAt: now(),
      updatedAt: now(),
    },
  ];

  return {
    ...store,
    users: [admin, owner],
    salons,
    services,
  };
};
